[package]
name = "auth"
version = "0.1.0"
edition = "2024"

[dependencies]
axum.workspace = true
axum-extra.workspace = true
headers.workspace = true
http.workspace = true
sqlx.workspace = true
serde.workspace = true
argon2.workspace = true
async-trait.workspace = true
chrono.workspace = true
jsonwebtoken.workspace = true
uuid.workspace = true
validator.workspace = true
tracing.workspace = true
axum-valid.workspace = true
tonic.workspace = true

api.workspace = true
user.workspace = true
shared.workspace = true
