[workspace]
resolver = "3"
members = ["crates/api", "crates/auth", "crates/card", "crates/shared", "crates/user"]

[package]
name = "ptcg-collector"
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
tokio = { version = "1", features = ["full"] }
axum = { version = "0.8.9" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.149"
async-trait = "0.1.89"
uuid = { version = "1.23.1", features = ["v4", "v7", "serde"] }
argon2 = "0.5.3"
jsonwebtoken = { version = "10.4.0", features = ["rust_crypto"] }
dotenv = "0.15.0"
sqlx = { version = "0.8", features = [
  "runtime-tokio",
  "postgres",
  "tls-native-tls",
  "uuid",
  "chrono",
] }
chrono = { version = "0.4.44", features = ["serde"] }
tokio-util = { version = "0.7.18", features = ["rt"] }
tower = { version = "0.5", features = ["full"] }
tower-http = { version = "0.6", features = ["timeout", "cors"] }
axum-extra = { version = "0.12", features = ["cookie", "query", "typed-header"] }
headers = "0.4"
http = "1"
tracing = "0.1.44"

opentelemetry = { version = "0.32.0", features = ["metrics"] }
opentelemetry_sdk = { version = "0.32.0", features = ["trace", "metrics", "logs"] }
opentelemetry-stdout = { version = "0.32.0", features = ["trace", "metrics", "logs"] }
opentelemetry-appender-tracing = "0.32.0"
tracing-subscriber = { version = "0.3", features = ["registry", "env-filter"] }
validator = { version = "0.20.0", features = ["derive"] }
axum-valid = "0.24.0"
prost = "0.14.3"
prost-types = "0.14.3"
tonic = "0.14.6"
tonic-prost = "0.14.6"
tonic-health = "0.14.6"
tonic-reflection = "0.14.6"
regex = "1.12.4"
api = { path = "crates/api" }
user = { path = "crates/user" }
shared = { path = "crates/shared" }
card = { path = "crates/card" }


[dependencies]
tokio.workspace = true
axum.workspace = true
axum-extra.workspace = true
dotenv.workspace = true
tower.workspace = true
tower-http.workspace = true
headers.workspace = true
http.workspace = true
tracing.workspace = true
opentelemetry.workspace = true
opentelemetry_sdk.workspace = true
opentelemetry-stdout.workspace = true
opentelemetry-appender-tracing.workspace = true
tracing-subscriber.workspace = true
async-trait.workspace = true
sqlx.workspace = true
prost.workspace = true
tonic.workspace = true
tonic-prost.workspace = true
tonic-health.workspace = true
tonic-reflection.workspace = true
api = { path = "crates/api" }
shared = { path = "crates/shared" }
user = { path = "crates/user" }
auth = { path = "crates/auth" }
card = { path = "crates/card" }
